version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "06:15"
      timezone: "Europe/Copenhagen"
    assignees:
      - "nyvanga"

  - package-ecosystem: "docker"
    directory: "/multitool"
    schedule:
      interval: "weekly"
      time: "06:30"
      timezone: "Europe/Copenhagen"
    assignees:
      - "nyvanga"
