version: '3'

services:
  test_build_multitool_aws_v1:
    build: .
    image: test_build_multitool_aws_v1
    container_name: test_build_multitool_aws_v1
    volumes:
      - $HOME/.aws:/root/.aws
    entrypoint: ["/bin/sleep", "infinity"]